---
title: "Fungicides.Colletotrichum.Mexico.2"
author: "Nieto_Lopez"
date: "8/23/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, set packages, warning= FALSE, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ezec)
#library(NRES803)
library(broom)
library(ggridges)
library(cowplot)
library(gridExtra)
library(kableExtra)
library(arsenal)
library(DescTools)
library(knitr)
library(agricolae)
```


##  Statistic Analysis 


In the following section we will show the results for each fungicide


```{r function to take outliers from 6 observations}
# First function to move away outliers
get_range <- function(mynumber) {
  bb <- boxplot.stats(mynumber)
  cc <- bb$stats
  dd <- max(cc)
  ee <- min(cc)
  return(data.frame(upper = dd, lower = ee))
}

# Second function to get EC50

getting_EC50 <- function(filename){
  
  getting.EC50 <- EC_table(filename, form = response ~ dose)
getting.EC50 <- getting.EC50 %>% 
  rename(ID = sample ) %>% # renaming
  rename(EC50 = Estimate.50) %>%
  mutate(ID = as.factor(ID))
}

```


```{r read data}
#Reading function
reading_data <- function(filename){
  data <-
  read.csv(filename)
 # data <- subset(data, select = -X)
  data$repeats <- rep_len(1:3, length.out = nrow(data))
  
  data <- data %>%
         mutate(polar= replace(growth, growth == 0, 6)) %>%  #replacing 0 cm growth for the size of plug that is 0.6
     group_by(ID, experimental_replicate, concentration, growth, repeats) %>%
  rename(dose = concentration )
  }
###  Reading and subsetting data


Carbendazim.Colletotrichum.data.sinaloa <-
  reading_data("data/Carbendazim.Colletotrichum.citricos.sinaloa.csv")




 
```
# Carbendazim
##  Serial Dilution
```{r Serial dilution Colletotrichum Carbendazim,  warning=FALSE}
# Colletotrichum Carbendazim fungicide taking the outliers from the 6 observations of each one USING THE FUCTION
Carbendazim.filtered.sinaloa  <- Carbendazim.Colletotrichum.data.sinaloa %>%
  group_by(ID, dose) %>%
  mutate(growth_range = list(get_range(growth))) %>%
  unnest() %>%
  filter(growth <= upper & growth >= lower) %>%
  rename(response = growth) %>%
  ungroup() %>%
  select(c(ID, experimental_replicate, repeats, dose, response))

#Using the function to get eEC50 and summarizing
Carbendazim.Colletotrichum.EC50.sinaloa <- getting_EC50(Carbendazim.filtered.sinaloa) 

summary.Carbendazim.Colletotrichum.EC50.sinaloa <-summary(Carbendazim.Colletotrichum.EC50.sinaloa)

write.csv(Carbendazim.Colletotrichum.EC50.sinaloa, file = "outputs/Carbendazim.Colletotrichum.EC50.sinaloa.csv")
write.csv(summary.Carbendazim.Colletotrichum.EC50.sinaloa, file = "outputs/summary.Carbendazim.Colletotrichum.EC50.sinaloa.csv")
```


## Analyses 
```{r Analyses Colletotrichum Carbendazim}
##NORMALITY TEST-Shapiro_test

shapiro.test.Carbendazim.Colletotrichum.sinaloa <- Carbendazim.Colletotrichum.EC50.sinaloa %>%
    do(tidy(shapiro.test(.$EC50)))
  shapiro.test.Carbendazim.Colletotrichum.sinaloa[[2]][[1]]
  #They are NO Normal 1.265671e-11, thats is why  krusKal
#by ID

object.1 <- kruskal.test(EC50 ~ ID, data = Carbendazim.Colletotrichum.EC50.sinaloa)
object.1[[3]][[1]]
  
#There is no difference p-value = 0.4677383
  
  
  Carbendazim.Colletotrichum.EC50.sinaloa %>% ggplot( aes(x= ID, y=EC50)) + geom_point() + expand_limits( y = c(0, 0.77)) +scale_y_continuous(
 breaks = c(0, 0.5, 0.1, 0.2,  0.3, 0.4, 0.5, 0.6, 0.7, 0.8 ))

ggsave("Carbendazim.Colletotrichum.EC50.sinaloa.png")
  


```




