---
title: "Thiophanate.Mexico"
author: "Nieto_Lopez"
date: "3/22/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, set packages, warning= FALSE, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ezec)
#library(NRES803)
library(broom)
library(ggridges)
library(cowplot)
library(gridExtra)
library(kableExtra)
library(arsenal)
library(DescTools)
library(knitr)
library(agricolae)
```

#  Background   





```{r read data}
#Reading function
reading_data <- function(filename){
  data <-
  read.csv(filename)
 # data <- subset(data, select = -X)
  data$repeats <- rep_len(1:3, length.out = nrow(data))
  data$ID <- as.character(data$ID)
  ####Transforming to $ID to numeric
 data$ID <- as.numeric(data$ID)

  data <- data %>%
         mutate(polar= replace(polar, polar == 0, 6)) %>%  #replacing 0 cm growth for the size of plug that is 0.6
    mutate(ecuatorial= replace(ecuatorial, ecuatorial == 0, 6)) %>% #replacing 0 cm growth for the size of plug that is 0.6
    group_by(ID, experimental_replicate, concentration, ecuatorial, polar, repeats) %>%
    mutate(growth = ((ecuatorial + polar) / 2)) %>%
  rename(dose = concentration )
  }
###  Reading and subsetting data

macrophomina.data <-
  reading_data("data/thiophanate.methyl.macrophomina.csv")
sclerotium.data <-
  reading_data("data/thiopahanate.methyl.sclerotium.rolfsii.2.csv")

##  Reading sclerotium data wher number of sclerotia was recorder as response variable
 
  sclerotium.data.sclerotia <-  read.csv("data/ thiophanate.methyl.athelia.rolfsii.sclerotia.csv")
 
  sclerotium.data.sclerotia$repeats <- rep_len(1:3,length.out = nrow(sclerotium.data.sclerotia))
  
   sclerotium.data.sclerotia$ID <- as.character(sclerotium.data.sclerotia$ID)
  ####Transforming to $ID to numeric
 sclerotium.data.sclerotia$ID <- as.numeric(sclerotium.data.sclerotia$ID)
 
```

##  Statistic Analysis 


In the following section we will show the results for each fungicide


```{r function to take outliers from 6 observations}
get_range <- function(mynumber) {
  bb <- boxplot.stats(mynumber)
  cc <- bb$stats
  dd <- max(cc)
  ee <- min(cc)
  return(data.frame(upper = dd, lower = ee))
}
```
#  Macrophomina
## Serial dilution

```{r Serial dilution Macrophomina, warning=FALSE}
# Macrophomina tebuconazole fungicide taking the outliers from the 6 observations of each one USING THE FUCTION
macrophomina.filtered  <- macrophomina.data %>%
  group_by(ID, dose) %>%
  mutate(growth_range = list(get_range(growth))) %>%
  unnest() %>%
  filter(growth <= upper & growth >= lower) %>%
  rename(response = growth) %>%
  ungroup() %>%
  select(c(ID, experimental_replicate, repeats, dose, response))

# Getting EC50 by EC_table #

getting_EC50 <- function(filename){
  
  getting.EC50 <- EC_table(filename, form = response ~ dose)
getting.EC50 <- getting.EC50 %>% 
  rename(ID = sample ) %>% # renaming
  rename(EC50 = Estimate.50) %>%
  mutate(ID = as.factor(ID))
}
#Using the function to get eEC50 and summarizing
macrophomina.EC50 <- getting_EC50(macrophomina.filtered) 

summary.macrophomina.EC50 <-summary(macrophomina.EC50)

write.csv(macrophomina.EC50, file = "outputs/thiophanate.methyl.macrophomina.EC50.csv") 
write.csv(summary.macrophomina.EC50, file = "outputs/thiophanate.methyl.macrophomina.summary. EC50.csv") 

```
## Analyses 
```{r Analyses macrophomina}
##NORMALITY TEST-Shapiro_test

shapiro.test.macrophomina <- macrophomina.EC50 %>%
    do(tidy(shapiro.test(.$EC50)))
  shapiro.test.macrophomina[[2]][[1]]
  #surprisingly they are normal
  
  #
AOV.1 <- (aov (EC50 ~ ID, data = macrophomina.EC50))
summary(AOV.1)
#P value of 0.805, there is no difference 
#ANOVA
 macrophomina.EC50 %>% ggplot( aes(x= ID, y=EC50))+ geom_point() 
#ggsave("thiophanate.methyl.macrophomina.EC50.png")

```

#  Sclerotium
## Num Sclerotia

```{r Num sclerotia, warning=FALSE}
#Sclerotium thiophanate fungicide taking the outliers from the 6 observations of each one USING THE FUCTION 
sclerotium.data.sclerotia.filtered  <- sclerotium.data.sclerotia%>%
  group_by(ID, concentration) %>%
  mutate(sclerotia_range = list(get_range(num_sclerotia))) %>%
  unnest() %>% 
  filter(num_sclerotia <= upper & num_sclerotia >= lower) %>%
  rename(response = num_sclerotia) %>%
  ungroup() %>%
  select(c(ID, experimental_replicate, concentration, response)) %>% 
group_by(ID, concentration ) %>% 
  summarise(mean_response = mean(response, na.rm = TRUE)) %>% 
  ungroup() %>%
  spread(concentration, mean_response) %>% 
  group_by(ID) %>% 
  mutate(Efficacy1 =  (((`0`-`1`) / `0`) * 100)) %>%    
     mutate(Efficacy5 = (((`0`-`5`) / `0`) * 100)) %>%
        mutate(Efficacy10 = (((`0`-`10`) / `0`) * 100)) %>%  
          mutate(Efficacy50 = (((`0`-`50`) / `0`) * 100)) %>%
            mutate(Efficacy100 = (((`0`-`100`) / `0`) * 100)) %>%
              mutate(Efficacy500 = (((`0`-`500`) / `0`) * 100)) %>% 
  ungroup() %>% 
  select(-c(`0`,`1`,`5`, `10`, `50`, `100`, `500`))

  
sclerotium.data.sclerotia.filtered <- round(sclerotium.data.sclerotia.filtered, 2)
sclerotium.data.sclerotia.filtered
write.csv(sclerotium.data.sclerotia.filtered, file = "outputs/thiophanate.methyl.sclerotium.sclerotia.csv")


```


## Serial dilution

```{r Serial dilution sclerotium,  warning=FALSE}

# Macrophomina tebuconazole fungicide taking the outliers from the 6 observations of each one USING THE FUCTION
sclerotium  <- sclerotium.data %>%
  group_by(ID, dose) %>%
  mutate(growth_range = list(get_range(growth))) %>%
  unnest() %>%
  filter(growth <= upper & growth >= lower) %>%
  rename(response = growth) %>%
  ungroup() %>%
  select(c(ID, experimental_replicate, repeats, dose, response))

#Using the function to get eEC50 and summarizing
sclerotium.EC50 <- getting_EC50(sclerotium) 

summary.sclerotium.EC50 <-summary(sclerotium.EC50)

write.csv(sclerotium.EC50, file = "outputs/thiophanate.methyl.sclerotium.EC50.csv") 
write.csv(summary.sclerotium.EC50, file = "outputs/thiophanate.methyl.sclerotium.summary. EC50.csv")

```
## Analyses
```{r Analyses sclerotium}

##NORMALITY TEST-Shapiro_test

shapiro.test.sclerotium <- sclerotium.EC50 %>%
    do(tidy(shapiro.test(.$EC50)))
  shapiro.test.sclerotium[[2]][[1]]
#No normals
  
  #NO NORMALILTY 0.00000125 , thats is why  krusKal
#by ID

object.1 <- kruskal.test(EC50 ~ ID, data = sclerotium.EC50)
object.1[[3]][[1]]

#There no is difference p-value = 0.4579297

#object.2 <-  DunnTest(EC50 ~ ID, data = sclerotium.yy, method = "bonferroni")
#object.2 

sclerotium.EC50 %>% ggplot( aes(x= ID, y=EC50)) + geom_point() + expand_limits( y = c(0, 27000)) +scale_y_continuous(
breaks = c(0, 500, 1000, 2000,  3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 20000))

#ggsave("thiophanate.methyl.sclerotium.EC50.png")
```

